### ISSUE TITLE
Validate `affineTransform` API

### ISSUE THREAD

**Issue by opatiny** [mljs/ransac#4]
@targos, do you agree with this API for the affine transform function?

The inputs of the functions are 3xN matrices consisting of the source and the destination points. The third dimension for Z must be padded with zeros. The output is an object containing the x and y translations as well as the angle in degrees.

```ts
export interface AffineTransformParameters {
  rotation: number;
  translation: { x: number; y: number };
}

export function getAffineTransform(
  source: Matrix,
  destination: Matrix,
): AffineTransformParameters;
```

**Comment by targos** [comment]
Discussed in person
